# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        R-version: [3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up R ${{ matrix.R-version }}
      uses: actions/setup-R@v1
      with:
        R-version: ${{ matrix.R-version }}
    - name: Install dependencies
      run: |
        install.packages("ggplot2")
        install.packages("stats")
        install.packages("tidyr")
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml 
        fail_ci_if_error: true
